version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mi_db
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - ./app:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_NAME=mi_db
      - DATABASE_USER=mi_usuario
      - DATABASE_PASSWORD=mi_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  pgdata:
